<?xml version="1.0" encoding="utf-8"?><Database Name="Qlcafe" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8UPVFUS;Initial Catalog=Qlcafe;Persist Security Info=True;User ID=SA" SettingsObjectName="Cafe.Properties.Settings" SettingsPropertyName="QlcafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ban" Member="Bans">
    <Type Name="Ban">
      <Column Name="MaBan" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoGhe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Ban_HoaDon" Member="HoaDons" ThisKey="MaBan" OtherKey="MaBan" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="MaCtHd" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuongMua" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Hang_ChiTietHoaDon" Member="Hang" ThisKey="MaHang" OtherKey="MaHang" Type="Hang" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="MaHD" OtherKey="MaHD" Type="HoaDon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hang" Member="Hangs">
    <Type Name="Hang">
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DonViTinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Hang_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="MaHang" OtherKey="MaHang" Type="ChiTietHoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHD" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNv" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgayBan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaTraTien" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="MaHD" OtherKey="MaHD" Type="ChiTietHoaDon" />
      <Association Name="Ban_HoaDon" Member="Ban" ThisKey="MaBan" OtherKey="MaBan" Type="Ban" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NHanVien_HoaDon" Member="NHanVien" ThisKey="MaNv" OtherKey="Manv" Type="NHanVien" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHanVien" Member="NHanViens">
    <Type Name="NHanVien">
      <Column Name="Manv" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHanVien_HoaDon" Member="HoaDons" ThisKey="Manv" OtherKey="MaNv" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.QuanLiCafe" Member="QuanLiCafes">
    <Type Name="QuanLiCafe">
      <Column Name="MaBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="DaTraTien" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ThanhTien" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SoLuongMua" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>