<?xml version="1.0" encoding="utf-8"?><Database Name="RUP_2" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-8UPVFUS;Initial Catalog=RUP_2;Persist Security Info=True;User ID=SA" SettingsObjectName="Rup_2.Properties.Settings" SettingsPropertyName="RUP_2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Type" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>