//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucHanh2ADO.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaiThucHanh2ADO.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3157467_vector_design_cup_off_coffee_isolated_on_a_white_background {
            get {
                object obj = ResourceManager.GetObject("3157467-vector-design-cup-off-coffee-isolated-on-a-white-background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3157467_vector_design_cup_off_coffee_isolated_on_a_white_background1 {
            get {
                object obj = ResourceManager.GetObject("3157467-vector-design-cup-off-coffee-isolated-on-a-white-background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hết hàng!.
        /// </summary>
        internal static string FrmBanHang_CboTenHang_SelectedIndexChanged_Hết_hàng_ {
            get {
                return ResourceManager.GetString("FrmBanHang_CboTenHang_SelectedIndexChanged_Hết_hàng_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mời kiểm tra lại!.
        /// </summary>
        internal static string FrmLogin_Error {
            get {
                return ResourceManager.GetString("FrmLogin_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khong tim thay.
        /// </summary>
        internal static string FrmNhanVien_buttonX6_Click_Khong_tim_thay {
            get {
                return ResourceManager.GetString("FrmNhanVien_buttonX6_Click_Khong_tim_thay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Ok !.
        /// </summary>
        internal static string FrmNhanVien_ThongBao_Not_Ok__ {
            get {
                return ResourceManager.GetString("FrmNhanVien_ThongBao_Not_Ok__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok ngon!.
        /// </summary>
        internal static string FrmNhanVien_ThongBao_Ok_ngon_ {
            get {
                return ResourceManager.GetString("FrmNhanVien_ThongBao_Ok_ngon_", resourceCulture);
            }
        }
    }
}
